# site settings
title: Daphne Poon
subtitle:
email: dpoon@hmc.edu
description: 'My name is Daphne, and I am a sophomore engineering major at Harvey Mudd College, looking for internships which allow me to improve the lives of those less privileged than myself using my background in robotics, software, and engineering.'
baseurl:  # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 340 E Foothill Blvd
city: Claremont
state: CA
zip_code: 91711
country: USA
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 5

# social settings
500px_url:
facebook_url:
github_url: https://github.com/u/daphne-poon
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com/da.phne.p
linkedin_url: https://www.linkedin.com/in/daphne-poon-sy
pinterest_url:
slack_url:
twitter_url: https://twitter.com/daphneeep

# build settings
markdown: kramdown

sass:
  style: compressed
